"""Tests for the expanded check-delivery.py: conformance levels and the
definitive language-consistency check (v1.13.0).

check-delivery.py is hyphen-named, so it is loaded by path via importlib.
Fixture projects are built in tmp_path so the test is hermetic.
"""
import importlib.util
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT_PATH = REPO_ROOT / "aurora" / "scripts" / "check-delivery.py"

_spec = importlib.util.spec_from_file_location("check_delivery", SCRIPT_PATH)
cd = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(cd)

BANNER = "> *Generated by [aurora@aurora-smart-home (esphome skill)](https://x)*"


def make_minimal(root: Path):
    """A project that should reach 'minimal' but not 'standard'."""
    (root / "README.md").write_text(f"# Thing\n\n{BANNER}\n\nA thing.\n", encoding="utf-8")
    esphome = root / "esphome"
    esphome.mkdir()
    (esphome / "thing.yaml").write_text("esphome:\n  name: thing\n", encoding="utf-8")


def add_standard(root: Path):
    """Upgrade a minimal project to satisfy the standard checks."""
    (root / "README.md").write_text(
        f"# Thing\n\n{BANNER}\n\n"
        "## What this does\nx\n## Installation\nx\n"
        "## Troubleshooting\nx\n## Recovery\nx\n",
        encoding="utf-8",
    )
    esphome = root / "esphome"
    for fname in ("INSTALL.md", "TROUBLESHOOTING.md"):
        (esphome / fname).write_text(f"# {fname}\n\n{BANNER}\n", encoding="utf-8")
    (esphome / "secrets.yaml.example").write_text("wifi_ssid: x\n", encoding="utf-8")


class TestConformanceLevels:
    def test_minimal_project_passes_minimal(self, tmp_path):
        make_minimal(tmp_path)
        results, _ = cd.run_checks(str(tmp_path))
        assert cd.highest_level_passed(results) == "minimal"

    def test_minimal_project_fails_standard(self, tmp_path):
        make_minimal(tmp_path)
        results, _ = cd.run_checks(str(tmp_path))
        gated = [r for r in results if cd.at_or_below(r.level, "standard")]
        assert not all(r.passed for r in gated)

    def test_full_project_passes_standard(self, tmp_path):
        make_minimal(tmp_path)
        add_standard(tmp_path)
        results, _ = cd.run_checks(str(tmp_path))
        assert cd.highest_level_passed(results) in ("standard", "strict")

    def test_missing_readme_reaches_no_level(self, tmp_path):
        (tmp_path / "esphome").mkdir()
        results, _ = cd.run_checks(str(tmp_path))
        assert cd.highest_level_passed(results) is None


class TestLanguageConsistency:
    def test_mixed_language_fails(self, tmp_path):
        make_minimal(tmp_path)
        add_standard(tmp_path)
        # Make the README Swedish while INSTALL stays English.
        (tmp_path / "README.md").write_text(
            f"# Sak\n\n{BANNER}\n\n"
            "## What this does\nDetta är en sak som mäter och styr huset.\n"
            "## Installation\nSå här gör du för att installera och köra.\n"
            "## Troubleshooting\nOm det inte fungerar så kan du felsöka.\n"
            "## Recovery\nÅterställ enheten om den slutar svara.\n",
            encoding="utf-8",
        )
        results = cd.check_language_consistency(tmp_path)
        assert results and not results[0].passed
        assert results[0].level == "strict"

    def test_all_english_passes(self, tmp_path):
        make_minimal(tmp_path)
        add_standard(tmp_path)
        results = cd.check_language_consistency(tmp_path)
        assert all(r.passed for r in results)

    def test_swedish_letters_detected(self):
        assert cd._looks_swedish("Återställ enheten när den slutar svara helt.")

    def test_code_fences_do_not_trigger_swedish(self):
        text = "# Title\n\nAll English prose here.\n\n```yaml\nfor: minutes\n```\n"
        assert not cd._looks_swedish(text)


class TestGatingHelper:
    def test_at_or_below_ordering(self):
        assert cd.at_or_below("minimal", "standard")
        assert cd.at_or_below("standard", "strict")
        assert not cd.at_or_below("strict", "standard")
