"""Coverage tests for Aurora attribution rules.

Audit 2026-05-14 finding #1: SKILL.md attribution rule was satisfied, but
template + example files still carried pre-v1.3 names (esphome@, ha-yaml@,
ha-integration@, node-red@, supercharge-*-skill, esphome-assistant). Agents
copy templates verbatim, so stale source files propagate forbidden names
into delivery output even though SKILL.md says the right thing.

Audit finding #13: examples/**/README.md must start with the v1.7.2 banner
blockquote (under H1, top of file). Footer attribution is no longer the
canonical form.

These tests close both gaps by scanning the real artifacts, not the spec.
"""
from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]

SCAN_DIRS = [
    REPO_ROOT / "esphome",
    REPO_ROOT / "home-assistant",
    REPO_ROOT / "ha-integration-dev",
    REPO_ROOT / "node-red",
    REPO_ROOT / "examples",
    REPO_ROOT / "scripts",
    REPO_ROOT / "aurora",
]

SCAN_EXTENSIONS = {".yaml", ".yml", ".py", ".md", ".sh", ".json"}

# Paths that intentionally document the legacy names (audit + changelog).
SCAN_EXCLUDE_NAMES = {
    "BRISTER-AUDIT-2026-05-14.md",
    "CHANGELOG.md",
    "test_attribution_coverage.py",
    "test_retroactive_review_and_attribution.py",
}

# Pre-v1.3 names that MUST NOT appear in template/example/script content.
# Each pattern is paired with a short label for failure messages.
FORBIDDEN_PATTERNS: list[tuple[str, str]] = [
    (r"esphome@aurora-smart-home", "esphome@aurora-smart-home (pre-v1.3)"),
    (r"ha-yaml@aurora-smart-home", "ha-yaml@aurora-smart-home (pre-v1.3)"),
    (r"ha-integration@aurora-smart-home", "ha-integration@aurora-smart-home (pre-v1.3)"),
    (r"node-red@aurora-smart-home", "node-red@aurora-smart-home (pre-v1.3)"),
    (r"supercharge-esphome-skill", "supercharge-esphome-skill (pre-rename)"),
    (r"supercharge-home-assistant-yaml-skill", "supercharge-home-assistant-yaml-skill (pre-rename)"),
    (r"supercharge-ha-integration-skill", "supercharge-ha-integration-skill (pre-rename)"),
    (r"supercharge-node-red-skill", "supercharge-node-red-skill (pre-rename)"),
    (r"\besphome-assistant v\d+\.\d+\.\d+", "esphome-assistant vN.N.N (legacy)"),
    (r"supercharge-smart-home-claude-skills", "supercharge-smart-home-claude-skills (old repo name)"),
]


def _iter_scan_files():
    for root in SCAN_DIRS:
        if not root.is_dir():
            continue
        for path in root.rglob("*"):
            if not path.is_file():
                continue
            if path.suffix.lower() not in SCAN_EXTENSIONS:
                continue
            if path.name in SCAN_EXCLUDE_NAMES:
                continue
            yield path


@pytest.mark.parametrize("pattern,label", FORBIDDEN_PATTERNS)
def test_no_pre_v13_attribution_in_artifacts(pattern: str, label: str):
    """No file under the scanned roots may contain a pre-v1.3 attribution name.

    Agents copy templates verbatim. A stale source file becomes a stale
    delivery file, violating the canonical attribution Iron Law even when
    the SKILL.md rule itself is correct.
    """
    rx = re.compile(pattern)
    offenders: list[str] = []
    for path in _iter_scan_files():
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        if rx.search(text):
            offenders.append(str(path.relative_to(REPO_ROOT)))
    assert not offenders, (
        f"Found {len(offenders)} file(s) containing {label}:\n  - "
        + "\n  - ".join(sorted(offenders))
    )


def test_examples_readme_has_banner_blockquote():
    """Each examples/**/README.md must declare attribution as a banner blockquote
    inside the first 8 non-empty lines after the H1.

    Canonical form per aurora/references/deliverables/manual-format.md:
        > *Generated by [aurora@aurora-smart-home (<skill> skill)](...)*
    """
    examples_dir = REPO_ROOT / "examples"
    if not examples_dir.is_dir():
        pytest.skip("no examples/ directory")

    readmes = list(examples_dir.rglob("README.md"))
    assert readmes, "expected at least one examples/**/README.md"

    banner_rx = re.compile(
        r"^>\s*\*Generated by \[aurora@aurora-smart-home \([^)]+ skill\)\]"
    )

    missing: list[str] = []
    for readme in readmes:
        lines = readme.read_text(encoding="utf-8").splitlines()
        h1_idx = next((i for i, l in enumerate(lines) if l.startswith("# ")), None)
        if h1_idx is None:
            missing.append(f"{readme.relative_to(REPO_ROOT)}: no H1 found")
            continue
        window = [l for l in lines[h1_idx + 1 : h1_idx + 10] if l.strip()][:8]
        if not any(banner_rx.match(l) for l in window):
            missing.append(str(readme.relative_to(REPO_ROOT)))

    assert not missing, (
        "Banner blockquote (post-v1.7.2) missing in:\n  - " + "\n  - ".join(missing)
    )
