"""Contract tests for the retroactive YAML review protocol (Plan 7) and the
'Generated by' attribution rule across all skill SKILL.md files.

Two unrelated concerns batched into one file because both are skill-level
contracts: they govern what agents emit. Splitting them would create file
sprawl without clarifying anything.
"""
import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
AURORA_ROOT = Path(__file__).resolve().parents[1]
RETRO_PATH = AURORA_ROOT / "references" / "validators" / "retroactive-yaml-review.md"
VOLT_SOUL_PATH = AURORA_ROOT / "souls" / "volt.md"

# Skill SKILL.md files that ship 'Generated by' attribution rules.
SKILL_MDS_WITH_ATTRIBUTION = [
    REPO_ROOT / "esphome" / "SKILL.md",
    REPO_ROOT / "home-assistant" / "SKILL.md",
    REPO_ROOT / "node-red" / "SKILL.md",
    REPO_ROOT / "ha-integration-dev" / "SKILL.md",
]

# Pre-v1.3 plugin names that should NEVER appear in 'Generated by' rules.
LEGACY_PLUGIN_PREFIXES = [
    "esphome@aurora-smart-home",
    "ha-yaml@aurora-smart-home",
    "node-red@aurora-smart-home",
    "ha-integration@aurora-smart-home",
]


# Retroactive YAML review protocol.

@pytest.fixture(scope="module")
def retro_text():
    assert RETRO_PATH.is_file(), f"{RETRO_PATH} missing"
    return RETRO_PATH.read_text(encoding="utf-8")


def test_retroactive_review_doc_exists():
    assert RETRO_PATH.is_file()


def test_retroactive_review_has_required_phases(retro_text):
    """Protocol must enumerate extract / validate / anchor / output phases
    so agents do not skip a step."""
    required_phases = ["Extract", "Validator Suite", "Anchor", "Tiered Output"]
    text_lower = retro_text.lower()
    missing = [p for p in required_phases if p.lower() not in text_lower]
    assert not missing, (
        f"retroactive-yaml-review.md is missing required phases: {missing}. "
        "Without each phase named, agents may skip extraction or anchoring."
    )


def test_retroactive_review_documents_line_anchoring(retro_text):
    """Every finding must be re-emitted with the line number from the user's
    input. Without anchoring, the user cannot locate the failure."""
    text_lower = retro_text.lower()
    assert re.search(r"line\s+number", text_lower), (
        "retroactive-yaml-review.md does not mandate line-number anchoring. "
        "Findings without line references force the user to search the YAML."
    )


def test_retroactive_review_lists_volt_validator_suite(retro_text):
    """Volt's set of validators must be enumerated so the order is intentional."""
    required = [
        "pin-validator",
        "conflict-validator",
        "i2c-address-validator",
        "voltage-level-validator",
        "ota-safety-validator",
        "version-validator",
        "entity-id-validator",
        "secrets-validator",
    ]
    missing = [v for v in required if v not in retro_text]
    assert not missing, (
        f"retroactive-yaml-review.md does not name Volt's validator suite "
        f"completely: {missing}."
    )


def test_retroactive_review_lists_sage_validator_suite(retro_text):
    """Sage runs a different subset for HA YAML — entity-id (consumer),
    version, secrets."""
    text_lower = retro_text.lower()
    assert "consumer mode" in text_lower, (
        "Sage's invocation must specify entity-id-validator in consumer mode "
        "for retroactive review (Sage references entities, does not produce them)."
    )


def test_retroactive_review_documents_no_autofix_rule(retro_text):
    """Auto-rewriting the user's YAML without confirmation is forbidden.
    The protocol must spell this out."""
    text_lower = retro_text.lower()
    assert "auto-fix" in text_lower or "auto-rewrit" in text_lower or "auto-fix" in text_lower, (
        "retroactive-yaml-review.md does not forbid auto-fixing user YAML."
    )


def test_retroactive_review_documents_pass_message(retro_text):
    """A clean pass must enumerate the validators run so 'no findings' does
    not get mistaken for 'did not look'."""
    text_lower = retro_text.lower()
    assert re.search(r"(✅|pass)", retro_text) and "validators run" in text_lower, (
        "retroactive-yaml-review.md does not specify the pass-message format "
        "that lists which validators were actually executed."
    )


def test_retroactive_review_references_tiered_format(retro_text):
    """Consistent with other validators in the suite."""
    assert "_tiered-errors.md" in retro_text, (
        "retroactive-yaml-review.md does not reference _tiered-errors.md."
    )


def test_volt_soul_references_retroactive_protocol():
    """Volt is the primary agent that handles ESPHome YAML review. Its soul
    must point at the protocol so the agent knows to follow it when the
    user pastes YAML."""
    volt_text = VOLT_SOUL_PATH.read_text(encoding="utf-8")
    assert "retroactive-yaml-review" in volt_text, (
        "volt.md does not reference retroactive-yaml-review.md. When the "
        "user pastes YAML, Volt has no instruction to follow the review "
        "protocol — it might treat the request as a generation task."
    )


# 'Generated by' attribution rule freshness.

@pytest.mark.parametrize("skill_path", SKILL_MDS_WITH_ATTRIBUTION, ids=lambda p: p.parent.name)
def test_skill_attribution_uses_current_plugin_name(skill_path):
    """No SKILL.md should instruct agents to emit pre-v1.3 plugin names in
    'Generated by' attributions. Since v1.3, aurora ships as a single
    'aurora@aurora-smart-home' plugin; the legacy names (esphome@...,
    ha-yaml@..., node-red@..., ha-integration@...) refer to plugins that
    no longer exist."""
    text = skill_path.read_text(encoding="utf-8")
    # Find every line that mentions an attribution prefix from the legacy list.
    offending = []
    for legacy in LEGACY_PLUGIN_PREFIXES:
        # Only flag if it appears inside a 'Generated by ...' or
        # 'generated_with' context (the rule template, not historical mentions).
        pattern = rf"(Generated by|generated_with).{{0,40}}{re.escape(legacy)}"
        for m in re.finditer(pattern, text):
            offending.append(m.group(0))
    assert not offending, (
        f"{skill_path.name} instructs agents to emit a pre-v1.3 plugin name "
        f"in the 'Generated by' attribution: {offending}. Update to the "
        f"current 'aurora@aurora-smart-home (<sub-skill> skill)' form."
    )


@pytest.mark.parametrize("skill_path", SKILL_MDS_WITH_ATTRIBUTION, ids=lambda p: p.parent.name)
def test_skill_attribution_uses_aurora_plugin_name(skill_path):
    """Positive assertion: the attribution rule MUST mention the current
    plugin name."""
    text = skill_path.read_text(encoding="utf-8")
    has_generated_by = bool(re.search(r"(Generated by|generated_with)", text))
    if not has_generated_by:
        pytest.skip(f"{skill_path.name} does not document an attribution rule")
    has_aurora = "aurora@aurora-smart-home" in text
    assert has_aurora, (
        f"{skill_path.name} documents an attribution rule but does not use "
        f"the current 'aurora@aurora-smart-home' plugin name."
    )


def test_skill_attribution_does_not_hardcode_version_inside_quoted_rule():
    """Hardcoded versions in attribution rules drift every release. None of
    the skills should bake a specific 'vX.Y.Z' into the rule template."""
    offenders = []
    for skill_path in SKILL_MDS_WITH_ATTRIBUTION:
        text = skill_path.read_text(encoding="utf-8")
        # Look for 'Generated by ... vX.Y.Z' patterns in the rule template
        for m in re.finditer(r"(Generated by|generated_with)[^\n]*v\d+\.\d+", text):
            offenders.append((skill_path.name, m.group(0)))
    assert not offenders, (
        f"Skill SKILL.md files hardcode versions in attribution rules: "
        f"{offenders}. Drop the version from the template — the rule should "
        f"identify the plugin, not the release. Versions drift every release "
        f"and stale comments accumulate in user files."
    )
