# Whole-House Energy Monitor
# Complete ESPHome configuration for energy monitoring
#
# Hardware:
#   - ESP32 DevKit (or ESP32-S3 for better ADC)
#   - SCT-013-000 CT clamp (100A)
#   - Burden resistor (33Ω for 100A CT)
#   - Bias circuit (voltage divider)
#
# Safety: CT clamps are non-invasive and safe.
# Never open CT secondary while current is flowing!

substitutions:
  device_name: "energy-monitor"
  friendly_name: "Energy Monitor"

  # CT clamp ADC pin
  ct_main_pin: "GPIO34"
  ct_circuit1_pin: "GPIO35"
  ct_circuit2_pin: "GPIO32"

  # Calibration values (adjust after calibration)
  # Formula: actual_watts = adc_reading * calibration
  main_calibration: "111.1"      # For SCT-013-000 with 33Ω burden
  circuit1_calibration: "30.0"   # For SCT-013-030
  circuit2_calibration: "30.0"

  # Voltage (assumed, or measured with AC adapter)
  mains_voltage: "230"

  # Electricity price per kWh
  electricity_price: "0.15"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${device_name}-fallback"

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: INFO

# =============================================================================
# Time (for energy calculations)
# =============================================================================

time:
  - platform: homeassistant
    id: ha_time

# =============================================================================
# ADC Sensors (Raw CT readings)
# =============================================================================

sensor:
  # Main feed CT clamp (raw ADC)
  - platform: adc
    pin: ${ct_main_pin}
    id: ct_main_adc
    attenuation: 11db
    update_interval: 200ms
    internal: true

  # Circuit 1 CT (raw ADC)
  - platform: adc
    pin: ${ct_circuit1_pin}
    id: ct_circuit1_adc
    attenuation: 11db
    update_interval: 200ms
    internal: true

  # Circuit 2 CT (raw ADC)
  - platform: adc
    pin: ${ct_circuit2_pin}
    id: ct_circuit2_adc
    attenuation: 11db
    update_interval: 200ms
    internal: true

  # =============================================================================
  # Main Power (CT Clamp processed)
  # =============================================================================

  - platform: ct_clamp
    sensor: ct_main_adc
    name: "${friendly_name} Power"
    id: main_power
    sample_duration: 200ms
    update_interval: 2s
    filters:
      - calibrate_linear:
          method: least_squares
          datapoints:
            - 0.0 -> 0
            - 0.0295 -> 100     # Calibrate with 100W load
            - 0.059 -> 200      # Calibrate with 200W load
            - 0.295 -> 1000     # Calibrate with 1000W load
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1
    unit_of_measurement: "W"
    accuracy_decimals: 0
    device_class: power
    state_class: measurement

  # Circuit 1 Power
  - platform: ct_clamp
    sensor: ct_circuit1_adc
    name: "${friendly_name} Circuit 1"
    id: circuit1_power
    sample_duration: 200ms
    update_interval: 5s
    filters:
      - calibrate_linear:
          - 0.0 -> 0
          - 0.033 -> 100
    unit_of_measurement: "W"
    accuracy_decimals: 0
    device_class: power

  # Circuit 2 Power
  - platform: ct_clamp
    sensor: ct_circuit2_adc
    name: "${friendly_name} Circuit 2"
    id: circuit2_power
    sample_duration: 200ms
    update_interval: 5s
    filters:
      - calibrate_linear:
          - 0.0 -> 0
          - 0.033 -> 100
    unit_of_measurement: "W"
    accuracy_decimals: 0
    device_class: power

  # =============================================================================
  # Energy Calculations
  # =============================================================================

  # Daily energy (kWh)
  - platform: total_daily_energy
    name: "${friendly_name} Daily Energy"
    id: daily_energy
    power_id: main_power
    unit_of_measurement: "kWh"
    accuracy_decimals: 2
    filters:
      - multiply: 0.001  # Wh to kWh
    device_class: energy
    state_class: total_increasing

  # Current (estimated from power)
  - platform: template
    name: "${friendly_name} Current"
    unit_of_measurement: "A"
    accuracy_decimals: 1
    device_class: current
    lambda: return id(main_power).state / ${mains_voltage};
    update_interval: 5s

  # Daily cost
  - platform: template
    name: "${friendly_name} Daily Cost"
    id: daily_cost
    unit_of_measurement: "€"
    accuracy_decimals: 2
    icon: "mdi:currency-eur"
    lambda: return id(daily_energy).state * ${electricity_price};
    update_interval: 60s

  # Power factor (estimated - requires voltage measurement for accurate)
  - platform: template
    name: "${friendly_name} Power Factor"
    unit_of_measurement: ""
    accuracy_decimals: 2
    icon: "mdi:angle-acute"
    lambda: return 0.95;  # Assumed, update if you have voltage reference
    update_interval: 60s

  # WiFi signal
  - platform: wifi_signal
    name: "${friendly_name} WiFi"
    update_interval: 60s
    entity_category: diagnostic

  - platform: uptime
    name: "${friendly_name} Uptime"
    entity_category: diagnostic

# =============================================================================
# Binary Sensors (Alerts)
# =============================================================================

binary_sensor:
  # High power usage (> 3000W)
  - platform: template
    name: "${friendly_name} High Usage"
    device_class: power
    lambda: return id(main_power).state > 3000;

  # Very high usage (> 5000W) - potential overload
  - platform: template
    name: "${friendly_name} Overload Warning"
    device_class: problem
    lambda: return id(main_power).state > 5000;

  - platform: status
    name: "${friendly_name} Status"

# =============================================================================
# Text Sensors
# =============================================================================

text_sensor:
  - platform: template
    name: "${friendly_name} Usage Level"
    lambda: |-
      float power = id(main_power).state;
      if (power < 500) return {"Low"};
      if (power < 1500) return {"Normal"};
      if (power < 3000) return {"Moderate"};
      if (power < 5000) return {"High"};
      return {"Very High"};
    update_interval: 10s

  - platform: version
    name: "${friendly_name} ESPHome Version"
    entity_category: diagnostic

# =============================================================================
# Buttons
# =============================================================================

button:
  - platform: restart
    name: "${friendly_name} Restart"
    entity_category: config

# =============================================================================
# Optional: AC Voltage Reference
# =============================================================================

# Uncomment if using AC-AC adapter for voltage measurement
# (more accurate power calculation)
#
# sensor:
#   - platform: adc
#     pin: GPIO33
#     id: voltage_adc
#     attenuation: 11db
#     internal: true
#
#   - platform: template
#     name: "${friendly_name} Voltage"
#     unit_of_measurement: "V"
#     device_class: voltage
#     lambda: |-
#       // Calculate RMS voltage from ADC
#       // Calibrate multiplier based on your transformer ratio
#       return id(voltage_adc).state * 230.0;

# =============================================================================
# Optional: OLED Display
# =============================================================================

# Uncomment for local display
# i2c:
#   sda: GPIO21
#   scl: GPIO22
#
# display:
#   - platform: ssd1306_i2c
#     model: "SSD1306 128x64"
#     lambda: |-
#       it.printf(0, 0, id(font), "Power: %.0fW", id(main_power).state);
#       it.printf(0, 20, id(font), "Today: %.2f kWh", id(daily_energy).state);
#       it.printf(0, 40, id(font), "Cost: €%.2f", id(daily_cost).state);
