#!/usr/bin/env python3
"""
aurora/scripts/check-delivery.py

Validates that an Aurora project folder meets the Project Structure Rule
and delivery contracts before the specialist declares delivery complete.

Iron Law 8 (Volt) and Iron Law 3 (Sage, Ada, River, Iris) both require
this script to pass before declaring delivery.

Usage:
    python aurora/scripts/check-delivery.py <project-folder>
    python aurora/scripts/check-delivery.py co2-air-quality/

    # Show all checks including passing ones:
    python aurora/scripts/check-delivery.py --verbose co2-air-quality/

Exit codes:
    0  all checks passed
    1  one or more checks failed
"""

import argparse
import re
import sys
from pathlib import Path
from typing import NamedTuple


ATTRIBUTION_PATTERN = re.compile(
    r"Generated by \[aurora@aurora-smart-home"
)

BOM_DATESTAMP_PATTERN = re.compile(
    r"\b(?:January|February|March|April|May|June|July|August|"
    r"September|October|November|December)\s+\d{4}\b"
    r"|\b\d{4}-\d{2}\b"
)

README_REQUIRED_SECTIONS = [
    "What this does",
    "Installation",
    "Troubleshooting",
    "Recovery",
]

CANONICAL_SUBDIRS = {
    "esphome",
    "automations",
    "scripts",
    "blueprints",
    "packages",
    "dashboards",
    "node-red-flows",
    "custom_components",
    "hardware",
}

ALLOWED_ROOT_FILES = {
    "README.md",
    "aurora-project.json",
    "hacs.json",
    "LICENSE",
    ".github",
}

PCB_FILES = [
    "SCHEMATIC.md",
    "PCB-NOTES.md",
    "MANUFACTURING.md",
    "COST-ANALYSIS.md",
    "CERTIFICATION.md",
    "TEST-JIG.md",
]

SWEDISH_MARKERS = re.compile(
    r"\b(?:och|att|med|för|på|är|det|som|av|till|den|en|ett|vi|du|"
    r"han|hon|de|sig|men|om|så|kan|ha|ska|vill|från|inte)\b",
    re.IGNORECASE,
)


class CheckResult(NamedTuple):
    name: str
    passed: bool
    message: str


def check_root_readme(project: Path) -> list[CheckResult]:
    results: list[CheckResult] = []
    readme = project / "README.md"

    exists = readme.exists()
    results.append(CheckResult(
        "README.md exists",
        exists,
        "OK" if exists else f"MISSING: {readme}",
    ))

    if not exists:
        return results

    content = readme.read_text(encoding="utf-8", errors="replace")

    has_attribution = bool(ATTRIBUTION_PATTERN.search(content))
    results.append(CheckResult(
        "README.md attribution banner",
        has_attribution,
        "OK" if has_attribution else "MISSING: aurora attribution banner under H1",
    ))

    for section in README_REQUIRED_SECTIONS:
        found = section.lower() in content.lower()
        results.append(CheckResult(
            f"README.md section '{section}'",
            found,
            "OK" if found else f"MISSING: '## {section}' heading",
        ))

    return results


def check_esphome(project: Path) -> list[CheckResult]:
    results: list[CheckResult] = []
    esphome = project / "esphome"

    if not esphome.exists():
        return results

    for fname in ("INSTALL.md", "TROUBLESHOOTING.md"):
        fpath = esphome / fname
        exists = fpath.exists()
        results.append(CheckResult(
            f"esphome/{fname} exists",
            exists,
            "OK" if exists else f"MISSING: {fpath}",
        ))
        if exists:
            content = fpath.read_text(encoding="utf-8", errors="replace")
            has_attr = bool(ATTRIBUTION_PATTERN.search(content))
            results.append(CheckResult(
                f"esphome/{fname} attribution",
                has_attr,
                "OK" if has_attr else f"MISSING: attribution banner in esphome/{fname}",
            ))

    yaml_files = [
        f for f in esphome.glob("*.yaml")
        if f.stem not in ("secrets", "secrets.yaml")
    ]
    has_yaml = len(yaml_files) > 0
    results.append(CheckResult(
        "esphome/ device YAML",
        has_yaml,
        "OK" if has_yaml else "MISSING: no device .yaml file in esphome/",
    ))

    secrets_example = esphome / "secrets.yaml.example"
    exists = secrets_example.exists()
    results.append(CheckResult(
        "esphome/secrets.yaml.example exists",
        exists,
        "OK" if exists else f"MISSING: {secrets_example}",
    ))

    return results


def check_hardware(project: Path) -> list[CheckResult]:
    results: list[CheckResult] = []
    hardware = project / "hardware"
    esphome = project / "esphome"

    # PCB files must NOT be in esphome/ (v1.8.0+ rule)
    if esphome.exists():
        for fname in PCB_FILES:
            wrong = esphome / fname
            if wrong.exists():
                results.append(CheckResult(
                    f"PCB file location: {fname}",
                    False,
                    f"WRONG LOCATION: {fname} is in esphome/ — move to hardware/ (v1.8.0+)",
                ))

    if not hardware.exists():
        return results

    hazard = hardware / "HAZARD-ANALYSIS.md"
    if hazard.exists():
        content = hazard.read_text(encoding="utf-8", errors="replace")
        has_attr = bool(ATTRIBUTION_PATTERN.search(content))
        results.append(CheckResult(
            "hardware/HAZARD-ANALYSIS.md attribution",
            has_attr,
            "OK" if has_attr else "MISSING: attribution banner in HAZARD-ANALYSIS.md",
        ))

    return results


def check_bom(project: Path) -> list[CheckResult]:
    results: list[CheckResult] = []

    candidates = [
        project / "README.md",
        project / "hardware" / "BOM.md",
        project / "esphome" / "BOM.md",
    ]

    for bom_path in candidates:
        if not bom_path.exists():
            continue
        content = bom_path.read_text(encoding="utf-8", errors="replace")

        # Only check files that actually contain a BOM
        has_bom_marker = "bom" in content.lower() or "bill of material" in content.lower()
        has_table = "| " in content
        if not (has_bom_marker and has_table):
            continue

        has_datestamp = bool(BOM_DATESTAMP_PATTERN.search(content))
        label = bom_path.relative_to(project)
        results.append(CheckResult(
            f"BOM datestamp in {label}",
            has_datestamp,
            "OK" if has_datestamp
            else f"MISSING: price datestamp in {label} (format: 'Month YYYY' or 'YYYY-MM')",
        ))
        break

    return results


def check_subdir_structure(project: Path) -> list[CheckResult]:
    results: list[CheckResult] = []

    for item in project.iterdir():
        name = item.name
        if name.startswith(".") and name not in ALLOWED_ROOT_FILES:
            continue
        if item.is_file() and name not in ALLOWED_ROOT_FILES:
            results.append(CheckResult(
                f"Unexpected root file: {name}",
                False,
                f"WRONG LOCATION: {name} at project root — move to canonical subdirectory",
            ))
        elif item.is_dir() and name not in CANONICAL_SUBDIRS and name not in ALLOWED_ROOT_FILES:
            results.append(CheckResult(
                f"Unexpected subdirectory: {name}",
                False,
                f"UNEXPECTED: '{name}' is not a canonical subdirectory per Project Structure Rule",
            ))

    return results


def check_install_language(project: Path) -> list[CheckResult]:
    """
    Heuristic: if README.md reads as Swedish, INSTALL.md should too.
    Flags obvious language mismatches — not a definitive check.
    """
    results: list[CheckResult] = []

    readme = project / "README.md"
    install = project / "esphome" / "INSTALL.md"

    if not readme.exists() or not install.exists():
        return results

    readme_content = readme.read_text(encoding="utf-8", errors="replace")
    install_content = install.read_text(encoding="utf-8", errors="replace")

    readme_sv = len(SWEDISH_MARKERS.findall(readme_content)) >= 5
    install_sv = len(SWEDISH_MARKERS.findall(install_content)) >= 3

    if readme_sv and not install_sv:
        results.append(CheckResult(
            "INSTALL.md language vs README.md",
            False,
            "MISMATCH: README.md appears Swedish but INSTALL.md appears English — Language Rule violation",
        ))

    return results


def run_checks(project_path: str) -> tuple[list[CheckResult], bool]:
    project = Path(project_path)

    if not project.exists():
        print(f"ERROR: not found: {project}", file=sys.stderr)
        sys.exit(1)

    if not project.is_dir():
        print(f"ERROR: not a directory: {project}", file=sys.stderr)
        sys.exit(1)

    all_results: list[CheckResult] = []
    all_results.extend(check_root_readme(project))
    all_results.extend(check_esphome(project))
    all_results.extend(check_hardware(project))
    all_results.extend(check_bom(project))
    all_results.extend(check_subdir_structure(project))
    all_results.extend(check_install_language(project))

    overall_pass = all(r.passed for r in all_results)
    return all_results, overall_pass


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Validate an Aurora project folder against delivery rules."
    )
    parser.add_argument("project", help="Path to the project folder to validate")
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Show all checks including passing ones",
    )
    args = parser.parse_args()

    results, passed = run_checks(args.project)

    failures = [r for r in results if not r.passed]
    successes = [r for r in results if r.passed]

    project_label = Path(args.project).resolve()
    print(f"\nauora check-delivery — {project_label}\n{'─' * 62}")

    if args.verbose:
        for r in successes:
            print(f"  PASS  {r.name}")

    for r in failures:
        print(f"  FAIL  {r.name}")
        print(f"        {r.message}")

    total = len(results)
    failed_count = len(failures)
    print(f"{'─' * 62}\n  {total - failed_count}/{total} checks passed")

    if passed:
        print("\n  DELIVERY APPROVED — all checks passed\n")
    else:
        print(f"\n  DELIVERY BLOCKED — {failed_count} check(s) failed")
        print("  Fix the issues above, then re-run check-delivery.py.\n")

    sys.exit(0 if passed else 1)


if __name__ == "__main__":
    main()
