#!/bin/bash
#
# ESPHome Secrets Generator
# =========================
# Generates secure secrets for ESPHome configurations.
#
# Usage:
#     ./generate_secrets.sh              # Print to console
#     ./generate_secrets.sh --output     # Create secrets.yaml file
#     ./generate_secrets.sh --help       # Show help
#
# Generated by esphome@aurora-smart-home
# https://github.com/tonylofgren/aurora-smart-home

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Default values
OUTPUT_FILE=""
WIFI_SSID="YOUR_WIFI_SSID"
WIFI_PASSWORD="YOUR_WIFI_PASSWORD"
API_KEY_ONLY=false

# Generate a 32-byte base64-encoded API key
generate_api_key() {
    openssl rand -base64 32
}

# Generate a URL-safe password
generate_password() {
    local length=${1:-16}
    openssl rand -base64 "$length" | tr -d '/+=' | head -c "$length"
}

# Generate AP password (8 hex chars)
generate_ap_password() {
    openssl rand -hex 4
}

# Print secrets to console
print_secrets() {
    echo "============================================================"
    echo "ESPHome Secrets Generator"
    echo "============================================================"
    echo ""
    echo "API Encryption Key (for api: encryption: key:)"
    echo "  $(generate_api_key)"
    echo ""
    echo "OTA Password (for ota: password:)"
    echo "  $(generate_password 12)"
    echo ""
    echo "Fallback AP Password (optional)"
    echo "  $(generate_ap_password)"
    echo ""
    echo "============================================================"
    echo "Copy these values to your secrets.yaml file"
    echo "Or run with --output to generate a complete file"
    echo "============================================================"
}

# Create secrets.yaml file
create_secrets_file() {
    local api_key=$(generate_api_key)
    local ota_pass=$(generate_password 12)
    local ap_pass=$(generate_ap_password)

    cat > "$OUTPUT_FILE" << EOF
# ESPHome Secrets File
# Generated by generate_secrets.sh
# https://github.com/tonylofgren/aurora-smart-home
#
# IMPORTANT: Keep this file secret! Add to .gitignore

# WiFi credentials
wifi_ssid: "${WIFI_SSID}"
wifi_password: "${WIFI_PASSWORD}"

# API encryption key (32 bytes, base64 encoded)
# Used for secure communication with Home Assistant
api_encryption_key: "${api_key}"

# OTA (Over-The-Air) update password
ota_password: "${ota_pass}"

# Fallback AP password (used when WiFi connection fails)
ap_password: "${ap_pass}"

# Optional: Additional secrets
# mqtt_username: "your_mqtt_user"
# mqtt_password: "your_mqtt_password"
# web_server_password: "your_web_password"
EOF
}

# Show help
show_help() {
    cat << EOF
ESPHome Secrets Generator

Usage: $(basename "$0") [OPTIONS]

Options:
    -o, --output [FILE]     Create secrets file (default: secrets.yaml)
    --wifi-ssid SSID        WiFi SSID to include
    --wifi-password PASS    WiFi password to include
    --api-key-only          Only output an API encryption key
    -h, --help              Show this help message

Examples:
    $(basename "$0")                              # Print secrets to console
    $(basename "$0") --output                     # Create secrets.yaml
    $(basename "$0") -o my_secrets.yaml           # Custom filename
    $(basename "$0") --wifi-ssid "MyNetwork"      # Include WiFi details
EOF
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -o|--output)
            if [[ -n "$2" && ! "$2" =~ ^- ]]; then
                OUTPUT_FILE="$2"
                shift 2
            else
                OUTPUT_FILE="secrets.yaml"
                shift
            fi
            ;;
        --wifi-ssid)
            WIFI_SSID="$2"
            shift 2
            ;;
        --wifi-password)
            WIFI_PASSWORD="$2"
            shift 2
            ;;
        --api-key-only)
            API_KEY_ONLY=true
            shift
            ;;
        -h|--help)
            show_help
            exit 0
            ;;
        *)
            echo -e "${RED}Unknown option: $1${NC}"
            show_help
            exit 1
            ;;
    esac
done

# Main logic
if $API_KEY_ONLY; then
    generate_api_key
    exit 0
fi

if [[ -n "$OUTPUT_FILE" ]]; then
    # Check if file exists
    if [[ -f "$OUTPUT_FILE" ]]; then
        echo -n "$OUTPUT_FILE already exists. Overwrite? [y/N] "
        read -r response
        if [[ ! "$response" =~ ^[Yy]$ ]]; then
            echo "Aborted."
            exit 1
        fi
    fi

    create_secrets_file
    echo -e "${GREEN}✓ Created $OUTPUT_FILE${NC}"
    echo ""
    echo "Next steps:"
    echo "  1. Edit $OUTPUT_FILE and add your WiFi credentials"
    echo "  2. Add '$OUTPUT_FILE' to your .gitignore"
    echo "  3. Reference secrets in your ESPHome config with !secret"
else
    print_secrets
fi
