#!/usr/bin/env python3
"""
ESPHome Secrets Generator
=========================
Generates secure secrets for ESPHome configurations.

Usage:
    python generate_secrets.py              # Print to console
    python generate_secrets.py --output     # Create secrets.yaml file
    python generate_secrets.py --help       # Show help

Generated by esphome@aurora-smart-home
https://github.com/tonylofgren/aurora-smart-home
"""

import secrets
import base64
import argparse
import sys
from pathlib import Path


def generate_api_key() -> str:
    """Generate a 32-byte base64-encoded API encryption key."""
    return base64.b64encode(secrets.token_bytes(32)).decode('utf-8')


def generate_password(length: int = 16) -> str:
    """Generate a URL-safe password."""
    return secrets.token_urlsafe(length)


def generate_wifi_ap_password() -> str:
    """Generate a simple AP fallback password (8 chars)."""
    return secrets.token_hex(4)


def create_secrets_yaml(
    wifi_ssid: str = "YOUR_WIFI_SSID",
    wifi_password: str = "YOUR_WIFI_PASSWORD"
) -> str:
    """Generate complete secrets.yaml content."""
    api_key = generate_api_key()
    ota_pass = generate_password(12)
    ap_pass = generate_wifi_ap_password()

    return f"""# ESPHome Secrets File
# Generated by generate_secrets.py
# https://github.com/tonylofgren/aurora-smart-home
#
# IMPORTANT: Keep this file secret! Add to .gitignore

# WiFi credentials
wifi_ssid: "{wifi_ssid}"
wifi_password: "{wifi_password}"

# API encryption key (32 bytes, base64 encoded)
# Used for secure communication with Home Assistant
api_encryption_key: "{api_key}"

# OTA (Over-The-Air) update password
ota_password: "{ota_pass}"

# Fallback AP password (used when WiFi connection fails)
ap_password: "{ap_pass}"

# Optional: Additional secrets
# mqtt_username: "your_mqtt_user"
# mqtt_password: "your_mqtt_password"
# web_server_password: "your_web_password"
"""


def print_secrets():
    """Print generated secrets to console."""
    print("=" * 60)
    print("ESPHome Secrets Generator")
    print("=" * 60)
    print()
    print("API Encryption Key (for api: encryption: key:)")
    print(f"  {generate_api_key()}")
    print()
    print("OTA Password (for ota: password:)")
    print(f"  {generate_password(12)}")
    print()
    print("Fallback AP Password (optional)")
    print(f"  {generate_wifi_ap_password()}")
    print()
    print("=" * 60)
    print("Copy these values to your secrets.yaml file")
    print("Or run with --output to generate a complete file")
    print("=" * 60)


def main():
    parser = argparse.ArgumentParser(
        description="Generate secure secrets for ESPHome configurations",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python generate_secrets.py                    # Print secrets to console
  python generate_secrets.py --output           # Create secrets.yaml
  python generate_secrets.py -o my_secrets.yaml # Custom filename
  python generate_secrets.py --wifi-ssid "MyNetwork" --wifi-password "MyPass"
        """
    )

    parser.add_argument(
        '-o', '--output',
        nargs='?',
        const='secrets.yaml',
        metavar='FILE',
        help='Output to file (default: secrets.yaml)'
    )

    parser.add_argument(
        '--wifi-ssid',
        default='YOUR_WIFI_SSID',
        help='WiFi SSID to include in secrets.yaml'
    )

    parser.add_argument(
        '--wifi-password',
        default='YOUR_WIFI_PASSWORD',
        help='WiFi password to include in secrets.yaml'
    )

    parser.add_argument(
        '--api-key-only',
        action='store_true',
        help='Only output an API encryption key'
    )

    args = parser.parse_args()

    if args.api_key_only:
        print(generate_api_key())
        return

    if args.output:
        output_path = Path(args.output)

        if output_path.exists():
            response = input(f"{output_path} already exists. Overwrite? [y/N] ")
            if response.lower() != 'y':
                print("Aborted.")
                sys.exit(1)

        content = create_secrets_yaml(args.wifi_ssid, args.wifi_password)
        output_path.write_text(content)
        print(f"✓ Created {output_path}")
        print()
        print("Next steps:")
        print(f"  1. Edit {output_path} and add your WiFi credentials")
        print(f"  2. Add '{output_path}' to your .gitignore")
        print("  3. Reference secrets in your ESPHome config with !secret")
    else:
        print_secrets()


if __name__ == '__main__':
    main()
